export type NewsletterWeek = {
  week: number;
  subject: string;
  preview: string;
  title: string;
  body: string;
  cta?: { label: string; href: string };
};

export const ballPython52Week: NewsletterWeek[] = [
  {week:1,subject:"Welcome to Ball Python 101",preview:"Start your year of better reptile care.",title:"Welcome to the ScalesWiki 52-Week Ball Python Journey",body:"Over the next year, we'll cover practical ball python care one step at a time. This week, start with the basics: your goal is a safe enclosure, stable heat, appropriate humidity, clean water, and a calm routine. Save this series and work through one lesson each week.",cta:{label:"Explore Ball Python 101",href:"/guides/ball-python"}},
  {week:2,subject:"Is a ball python right for you?",preview:"A responsible choice starts before the purchase.",title:"Before You Bring One Home",body:"Ball pythons can be rewarding long-term companions, but they require consistent husbandry and a commitment that can span decades. Think about space, budget, feeding, vacations, veterinary access, and who will care for the animal if your circumstances change.",cta:{label:"Read the guide",href:"/guides/ball-python/is-a-ball-python-right-for-you"}},
  {week:3,subject:"Where ball pythons come from",preview:"Natural history makes husbandry easier to understand.",title:"Learn the Animal Before the Equipment",body:"Understanding a species' natural environment helps explain its behavior and care needs. Ball pythons are terrestrial, secretive snakes from parts of West and Central Africa. Their wild lives involve warm shelter, seasonal changes, and opportunities to hide.",cta:{label:"Natural history",href:"/guides/ball-python/natural-history"}},
  {week:4,subject:"Build the enclosure before the snake",preview:"Preparation beats troubleshooting.",title:"Prepare First",body:"Set up the enclosure before bringing your snake home. Install heat, hides, substrate, water, and monitoring equipment, then run the enclosure long enough to identify unstable temperatures or humidity before the animal arrives."},
  {week:5,subject:"Enclosure size: bigger is not the problem",preview:"Security and usable space matter more than a tiny box.",title:"Think in Usable Space",body:"A good enclosure gives the snake room to move while providing secure hiding places and a meaningful warm-to-cool gradient. The goal is not simply a large box; it is usable space with predictable environmental conditions."},
  {week:6,subject:"Create a real temperature gradient",preview:"One number is not enough.",title:"Warm Side, Cool Side",body:"A ball python should be able to choose between warmer and cooler areas. Measure temperatures where the snake actually rests rather than relying on the thermostat setting alone. Use reliable digital instruments and check multiple locations."},
  {week:7,subject:"Heat safely",preview:"Good heating is controlled heating.",title:"Heat Without Guesswork",body:"Heat sources need appropriate thermostatic control and safe installation. Avoid uncontrolled heat sources and inspect cords, guards, probes, and mounting points regularly. A stable system is more important than chasing a single perfect number."},
  {week:8,subject:"Humidity without panic",preview:"Consistency matters more than constant adjustment.",title:"Manage Humidity",body:"Humidity should support normal hydration and shedding without turning the enclosure into a permanently wet environment. Monitor it, understand your enclosure's ventilation, and make gradual adjustments instead of reacting to every short-term fluctuation."},
  {week:9,subject:"The hide box test",preview:"If your snake cannot hide comfortably, the enclosure needs work.",title:"Security Is a Husbandry Tool",body:"Provide secure hides that let the snake feel enclosed while resting. A snake that has appropriate security often settles more readily than one exposed in a sparse enclosure. Give the animal choices rather than forcing it to choose between security and temperature."},
  {week:10,subject:"Water and hydration",preview:"Clean water should always be available.",title:"The Water Routine",body:"Provide clean, accessible drinking water and replace it when soiled. Check the bowl during routine care and make sure its placement is stable. Hydration management is simple when it is treated as a daily husbandry habit."},
  {week:11,subject:"Choosing substrate",preview:"There is no single substrate for every setup.",title:"Choose for the Whole Enclosure",body:"Consider moisture management, cleanliness, safety, availability, and how the substrate works with your enclosure's ventilation. Whatever you choose, establish a routine for spot cleaning and complete replacement when appropriate."},
  {week:12,subject:"Your first month checklist",preview:"Let's turn the basics into a repeatable routine.",title:"A Simple Husbandry Routine",body:"Create a short checklist: water, temperature, humidity, enclosure condition, waste, feeding record, and behavior. A repeatable routine helps you notice trends instead of relying on memory."},
  {week:13,subject:"How often should you feed?",preview:"Feeding is a system, not a race.",title:"Build a Feeding Plan",body:"Feeding frequency depends on the snake's age, size, condition, prey size, and individual circumstances. Use a consistent record rather than copying a schedule blindly. The aim is appropriate growth and body condition, not maximum feeding."},
  {week:14,subject:"Prey size matters",preview:"Appropriate prey is part of responsible feeding.",title:"Match Prey to the Snake",body:"Choose prey that is appropriate for the individual animal and use a consistent method for evaluating body condition. Avoid escalating prey size simply because the snake accepts food readily."},
  {week:15,subject:"Frozen-thawed feeding",preview:"A predictable feeding routine can reduce risk.",title:"Make Feeding Boring",body:"Many keepers prefer frozen-thawed prey because it can be stored safely and used consistently. Follow appropriate thawing and warming practices, keep food-handling separate from normal food preparation, and never leave a feeding situation unattended."},
  {week:16,subject:"Keep a feeding log",preview:"Records turn observations into useful information.",title:"Track What Happens",body:"Record date, prey type and size, feeding response, and notable observations. Over time, a feeding log can reveal patterns and gives you useful information to share with a qualified reptile veterinarian if concerns arise."},
  {week:17,subject:"Why snakes sometimes skip meals",preview:"A missed meal is information, not automatically an emergency.",title:"Don't Panic Over One Refusal",body:"Food refusal can happen for many reasons, including routine changes, seasonal behavior, environmental problems, stress, or illness. Check husbandry first, track the pattern, and seek veterinary guidance when the situation is concerning or persistent."},
  {week:18,subject:"Handling basics",preview:"Calm handling starts with respecting the snake's body language.",title:"Handle With Purpose",body:"Support the snake's body, move slowly, and avoid unnecessary handling around stressful events such as feeding or shedding. Handling should be predictable and brief enough that the animal can return to normal behavior afterward."},
  {week:19,subject:"Reading body language",preview:"Your snake communicates through behavior.",title:"Notice the Small Signals",body:"Learn what normal resting, exploring, hiding, and defensive behavior looks like for your individual snake. Changes matter most when compared with that animal's own baseline."},
  {week:20,subject:"Shedding week",preview:"A good shed starts with good husbandry.",title:"Support the Shed",body:"During shed cycles, your snake may become less active and less interested in food. Keep husbandry stable, provide secure hides, and avoid unnecessary handling. Never pull retained skin from a snake."},
  {week:21,subject:"After the shed",preview:"A shed is an opportunity to observe your snake.",title:"Use the Shed as a Checkpoint",body:"Inspect the shed and note whether it appears complete. Pay attention to retained eye caps or tail-tip skin. If you have concerns about retained shed or the animal's condition, use qualified veterinary guidance rather than internet home remedies."},
  {week:22,subject:"Cleaning the enclosure",preview:"Clean enough to be safe, not chaotic.",title:"Build a Cleaning Rhythm",body:"Spot clean waste promptly, refresh soiled areas, clean water containers, and perform deeper cleaning according to the enclosure and substrate system. Avoid constantly stripping the enclosure if the animal is otherwise healthy and stable."},
  {week:23,subject:"Biosecurity basics",preview:"Good hygiene protects reptiles and people.",title:"Treat Every Enclosure as Its Own Environment",body:"Wash hands between animals, use dedicated equipment when practical, and isolate new animals appropriately. Biosecurity becomes much easier when it is a routine rather than a response to an outbreak."},
  {week:24,subject:"Quarantine new reptiles",preview:"New arrivals deserve their own plan.",title:"Quarantine Is More Than a Separate Tank",body:"A proper quarantine plan considers physical separation, equipment, cleaning, observation, and veterinary evaluation when indicated. Follow your veterinarian's recommendations for parasite screening and other health checks."},
  {week:25,subject:"Midyear husbandry audit",preview:"Halfway through the year: test the system.",title:"Audit Your Setup",body:"Today, check your thermometers, thermostat probes, heating equipment, enclosure locks, hides, water bowl, substrate, and records. Replace unreliable equipment before it becomes an emergency."},
  {week:26,subject:"Behavior changes worth noticing",preview:"Know your snake's normal before you worry about abnormal.",title:"Build a Baseline",body:"Track appetite, activity, defecation, shedding, posture, and typical hiding behavior. Trends are more useful than isolated observations, and a clear baseline helps a veterinarian understand what changed."},
  {week:27,subject:"When to call a reptile veterinarian",preview:"Knowing when to ask for help is good husbandry.",title:"Don't Diagnose From a Search Result",body:"Breathing difficulty, significant injury, persistent abnormal behavior, concerning discharge, severe weight change, or other unexplained health problems deserve professional assessment. Internet information can help you prepare questions, but it should not replace veterinary diagnosis or treatment."},
  {week:28,subject:"Safe transport",preview:"A trip to the vet should not become a second emergency.",title:"Prepare a Transport Plan",body:"Use a secure, appropriately ventilated container and protect the snake from temperature extremes. Keep transport time reasonable and bring useful husbandry and feeding records to veterinary appointments."},
  {week:29,subject:"Stress and enclosure placement",preview:"Where the enclosure sits can affect behavior.",title:"Think About the Room",body:"Consider traffic, noise, vibrations, direct sunlight, other pets, and temperature swings. A stable location can reduce unnecessary stress while still allowing you to monitor the enclosure easily."},
  {week:30,subject:"Lighting and day-night rhythm",preview:"A predictable environment helps establish routine.",title:"Give the Snake a Consistent Rhythm",body:"Maintain a predictable light and dark cycle appropriate to your setup. Avoid using bright lights as a substitute for correct heating and never assume lighting can compensate for poor temperature control."},
  {week:31,subject:"Enrichment for a ball python",preview:"Enrichment can be simple.",title:"Encourage Natural Behaviors",body:"Secure hides, varied textures, safe climbing opportunities where appropriate, and opportunities to explore can provide useful behavioral enrichment. Any enrichment item must be stable, non-toxic, and easy to inspect and clean."},
  {week:32,subject:"Common enclosure mistakes",preview:"Let's catch the easy-to-fix problems.",title:"Troubleshoot the Basics",body:"Common issues include poor measurement, unstable heat, insufficient hides, inappropriate ventilation, unsafe heating, and inconsistent cleaning. Start with measurable husbandry factors before making complicated changes."},
  {week:33,subject:"Why consistency wins",preview:"Reptile care is mostly about repeatable systems.",title:"Make Good Care Automatic",body:"The best setup is one you can maintain on busy weeks. Automate what is safe to automate, document your routine, and keep replacement supplies available so a small problem does not become a crisis."},
  {week:34,subject:"Budgeting for reptile care",preview:"The cheapest setup is not always the least expensive one.",title:"Budget for the Whole Animal",body:"Plan for enclosure equipment, electricity, food, substrate, replacement equipment, routine supplies, and veterinary care. A realistic budget reduces the temptation to delay necessary care."},
  {week:35,subject:"Finding a reptile veterinarian",preview:"Build the relationship before you need an emergency visit.",title:"Know Your Veterinary Options",body:"Identify a veterinarian who is comfortable treating reptiles and learn how to contact the clinic. Keep the information accessible, and ask about emergency coverage before an urgent situation happens."},
  {week:36,subject:"Responsible breeding and ownership",preview:"Every animal should have a plan beyond the purchase.",title:"Think Beyond Acquisition",body:"Responsible reptile keeping includes planning for long-term ownership, rehoming contingencies, and avoiding impulse purchases. Never release a captive reptile into the wild."},
  {week:37,subject:"Rescue and rehoming",preview:"A rescue animal deserves the same careful husbandry.",title:"Support Responsible Rehoming",body:"When a reptile needs a new home, prioritize accurate information, appropriate screening, and safe transfer. Rescue should be a bridge to stable care, not a reason to bypass responsible husbandry."},
  {week:38,subject:"Record keeping",preview:"Your notes can become your snake's care history.",title:"Build a Reptile Care File",body:"Keep feeding, shedding, weight, enclosure, veterinary, and major event records together. Digital records are especially useful when multiple people share care responsibilities."},
  {week:39,subject:"Weight tracking",preview:"A scale can tell you what your eyes cannot.",title:"Track Trends, Not Panic",body:"Periodic weight records can help you recognize meaningful changes. Use the same scale and similar conditions when possible, and interpret changes alongside appetite, behavior, and veterinary advice."},
  {week:40,subject:"Seasonal changes",preview:"Your room changes even when you don't notice it.",title:"Recheck the Enclosure as Seasons Change",body:"Indoor temperatures, humidity, and daylight can shift throughout the year. Recheck equipment and environmental readings during seasonal transitions instead of assuming last month's settings are still appropriate."},
  {week:41,subject:"Emergency preparedness",preview:"A small kit can save time when something goes wrong.",title:"Build a Reptile Emergency Kit",body:"Keep secure transport supplies, basic cleaning materials, contact information for veterinary care, and copies of important records ready. Do not stockpile medications or attempt treatments without veterinary direction."},
  {week:42,subject:"Internet advice: use the red X",preview:"Not everything labeled reptile care is reliable.",title:"Know When to Stop Searching",body:"Use reputable educational resources to learn husbandry and prepare questions. Put a red X on internet instructions that tell you to diagnose or treat illness or injury yourself. When health is involved, qualified veterinary care comes first."},
  {week:43,subject:"Social media reptile advice",preview:"Popular does not mean correct.",title:"Evaluate the Source",body:"Look for transparent sourcing, species-specific information, current husbandry standards, and professional review where appropriate. A confident video is not automatically a reliable medical or husbandry recommendation."},
  {week:44,subject:"Building your own care checklist",preview:"Turn knowledge into habits.",title:"Make a One-Page Routine",body:"Create a simple checklist for daily, weekly, monthly, and seasonal tasks. Keep it near the enclosure so good care remains easy even when life gets busy."},
  {week:45,subject:"Teaching someone else to care for your snake",preview:"A backup caregiver needs more than a food schedule.",title:"Create a Care Handoff",body:"Write down the enclosure settings, feeding plan, water routine, cleaning steps, emergency contacts, and what normal behavior looks like. A clear handoff protects the animal when someone else needs to provide care."},
  {week:46,subject:"Travel planning",preview:"Your snake still needs a stable routine while you're away.",title:"Plan Before the Trip",body:"Arrange a competent caregiver, leave written instructions, and make sure the enclosure and supplies are reliable before departure. Avoid last-minute husbandry changes just before travel."},
  {week:47,subject:"Upgrading an enclosure",preview:"Improve the system without changing everything at once.",title:"Upgrade Deliberately",body:"When you upgrade, move one major variable at a time when practical and verify the new enclosure's environmental stability. Give the snake time to settle after meaningful changes."},
  {week:48,subject:"What a healthy routine looks like",preview:"Good husbandry is often wonderfully boring.",title:"Stable Is the Goal",body:"A healthy routine includes predictable environmental conditions, normal appetite patterns for that individual, regular waste and shedding observations, and calm behavior. Stability is a success, not a lack of excitement."},
  {week:49,subject:"Review your year of records",preview:"Your own data can teach you a lot.",title:"Look for Patterns",body:"Review feeding, weight, shedding, environmental notes, and veterinary records from the year. Identify what worked and what you would change before the next season."},
  {week:50,subject:"Five things to improve this month",preview:"Small improvements compound.",title:"Choose the Highest-Value Fixes",body:"Pick a few practical improvements: verify measuring equipment, replace worn supplies, improve record keeping, organize veterinary information, or make the enclosure safer. Don't change things just to change them."},
  {week:51,subject:"From keeper to advocate",preview:"Good reptile keeping helps the whole community.",title:"Share Better Information",body:"Responsible keepers can improve reptile welfare by modeling good husbandry, correcting misinformation respectfully, supporting reputable rescues, and encouraging professional veterinary care when animals are sick."},
  {week:52,subject:"You made it through Ball Python 101",preview:"One year of learning is only the beginning.",title:"Keep Learning",body:"Congratulations on completing the 52-week journey. Use what you learned to keep refining your animal's care, and revisit the ScalesWiki Academy when you're ready for structured lessons, quizzes, exams, and certificates.",cta:{label:"Explore ScalesWiki Academy",href:"/academy"}},
];

export function getNewsletterWeek(week: number) {
  return ballPython52Week.find((item) => item.week === week);
}
